version: '3'

services:
  db-master:
    image: bitnami/mariadb:latest
    ports:
      - '3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_DATABASE=${PDNS_DB_NAME}
      - MARIADB_USER=${PDNS_DB_USER}
      - MARIADB_PASSWORD=${PDNS_DB_PASSWORD}
    networks:
      internal-db:
    volumes:
      - '${PDNS_DB_DATA_PATH}:/bitnami'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  db-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - db-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=db-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      internal-db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  admin-db-master:
    image: bitnami/mariadb:latest
    ports:
      - '3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_DATABASE=${PDA_DB_NAME}
      - MARIADB_USER=${PDA_DB_USER}
      - MARIADB_PASSWORD=${PDA_DB_PASSWORD}
    networks:
      internal-db:
    volumes:
      - '${PDA_DB_DATA_PATH}:/bitnami'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  admin-db-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - admin-db-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=admin-db-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      internal-db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  authoritative:
    image: psitrax/powerdns:latest
    restart: always
    ports:
      - '5300:53'
      - '5300:53/udp'
    links: 
      - db-master:db 
    command: [
      '--api=yes', '--api-key=${PDNS_API_KEY}', 
      '--disable-axfr=${PDNS_DISABLE_AXFR}', '--allow-axfr-ips=${PDNS_ALLOW_AXFR_IPS}',
      '--master=${PDNS_MASTER}', '--slave=${PDNS_SLAVE}', '--slave-cycle-interval=${PDNS_SLAVE_CYCLE_INTERNAL}',
      '--loglevel=${PDNS_LOGLEVEL}', '--log-dns-details=${PDNS_LOG_DNS_DETAILS}', '--log-dns-queries=${PDNS_LOG_DNS_QUERIES}',
      '--webserver-address=0.0.0.0', '--webserver-allow-from=0.0.0.0/0']
    depends_on: 
      - db-master
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${PDNS_DB_USER}
      - MYSQL_PASS=${PDNS_DB_PASSWORD}
    networks:
      internal:
        ipv4_address: ${DOCKER_PDNS_IP}
      internal-db:

  recursor:
    image: xyzxyz442/pdns-recursor:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    environment:
      - PDNS_forward_zones=${PDNS_RECURSOR_FORWARD_ZONES}
      - PDNS_forward_zones_recurse=${PDNS_RECURSOR_FORWARD_ZONES}
      - PDNS_loglevel=${PDNS_LOGLEVEL}
      - PDNS_log_common_errors=${PDNS_RECURSOR_LOG_COMMON_ERRORS}
    networks:
      internal:

  admin:
    build:
      context: .
      dockerfile: docker/PowerDNS-Admin/Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: pdns-admin
    ports:
      - '9191:9191'
    links: 
      - admin-db-master:db-admin
    depends_on:
      - authoritative
      - admin-db-master
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PDA_DB_HOST=db-admin
      - PDA_DB_NAME=${PDA_DB_NAME}
      - PDA_DB_USER=${PDA_DB_USER}
      - PDA_DB_PASSWORD=${PDA_DB_PASSWORD}
      - PDNS_HOST=${PDNS_HOST}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - FLASK_APP=/powerdns-admin/app/__init__.py
    networks:
      internal:
      internal-db:
    volumes:
      # Code
      - .:/powerdns-admin/
      - "./configs/${ENVIRONMENT}.py:/powerdns-admin/config.py"
      # Assets dir volume
      - powerdns-admin-assets:/powerdns-admin/app/static
      - powerdns-admin-assets2:/powerdns-admin/node_modules
      - '${PDA_LOGS_PATH}:/powerdns-admin/logs'
      - ./app/static/custom:/powerdns-admin/app/static/custom
    logging:
      driver: json-file
      options:
        max-size: 50m

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}
  internal-db:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_DB_SUBNET}

volumes:
  powerdns-admin-assets:
  powerdns-admin-assets2:
