version: '3.7'

services:
  pdns-db-master:
    image: bitnami/mariadb:latest
    ports:
      - '3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_DATABASE=${PDNS_DB_NAME}
      - MARIADB_USER=${PDNS_DB_USER}
      - MARIADB_PASSWORD=${PDNS_DB_PASSWORD}
    volumes:
      - '${PDNS_DB_DATA_PATH}:/bitnami'

  pdns-db-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - pdns-db-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=pdns-db-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  pdns-admin-db-master:
    image: bitnami/mariadb:latest
    ports:
      - '3306'
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_DATABASE=${PDA_DB_NAME}
      - MARIADB_USER=${PDA_DB_USER}
      - MARIADB_PASSWORD=${PDA_DB_PASSWORD}
    volumes:
      - '${PDA_DB_DATA_PATH}:/bitnami'

  pdns-admin-db-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - pdns-admin-db-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=pdns-admin-db-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  pdns:
    image: psitrax/powerdns:latest
    ports:
      - '53:53'
      - '53:53/udp'
    links: 
      - pdns-db-master:db
    command: --api=yes --api-key=${PDNS_API_KEY} --webserver-address=0.0.0.0 --webserver-allow-from=0.0.0.0/0
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${PDNS_DB_USER}
      - MYSQL_PASS=${PDNS_DB_PASSWORD}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}
    depends_on: 
      - pdns-db-master

  pdns-admin:
    build:
      context: .
      dockerfile: docker/PowerDNS-Admin/Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: pdns-admin
    ports:
      - '9191:9191'
    links: 
      - pdns-admin-db-master:db-admin
    volumes:
      # Code
      - .:/powerdns-admin/
      - "./configs/${ENVIRONMENT}.py:/powerdns-admin/config.py"
      # Assets dir volume
      - powerdns-admin-assets:/powerdns-admin/app/static
      - powerdns-admin-assets2:/powerdns-admin/node_modules
      - '${PDNS_ADMIN_LOGS_PATH}:/powerdns-admin/logs'
      - ./app/static/custom:/powerdns-admin/app/static/custom
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PDA_DB_HOST=db-admin
      - PDA_DB_NAME=${PDA_DB_NAME}
      - PDA_DB_USER=${PDA_DB_USER}
      - PDA_DB_PASSWORD=${PDA_DB_PASSWORD}
      - PDNS_HOST=${PDNS_HOST}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - FLASK_APP=/powerdns-admin/app/__init__.py
    depends_on:
      - pdns
      - pdns-admin-db-master

volumes:
  powerdns-admin-assets:
  powerdns-admin-assets2:
